[package]
name = "rl-algorithms"
version = "0.1.0"
authors = ["Tom Selfin <selfint@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.0"

[dev-dependencies]
rl-environments = { git = "https://github.com/tomaster777/rl-environments" , branch = "main"}
